# Generated by Django 4.2.20 on 2025-04-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_unique_together_producto_en_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estrellas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
