# Generated by Django 4.2.20 on 2025-04-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('categoria', 'nombre')},
        ),
    ]
